### PR TITLE
Don't require the DEAD tag to be first

### PR DESCRIPTION
**Pull request by ulm**

### CODE REVIEW

**Comment by mgorny** [comment]
It's not that I'm opposed to it, but is there a reason for it not to be the first tag?

**Comment by ulm** [comment]
> It's not that I'm opposed to it, but is there a reason for it not to be the first tag?

A specific position of the tag is not required by the policy that was accepted by the council in 2009, see gentoo/devmanual@afa883bdc680f187d249446f8d20ae9d7f5cdcc6.

Also, putting any tag in front of `@ECLASS` is also extremely counter-intuitive IMHO. I recently got it wrong for eutils.eclass, in spite of me adding that rule to the devmanual myself: gentoo/devmanual@cd392d0c6cd064ac3a1381111e678f4fe111afcc)

**Review by mgorny — APPROVED** [review]
*Shrug* if it works…

**Comment by ulm** [comment]
> _Shrug_ if it works…

I had verified that output is identical to the old version.

**Pull request merged**
